#Sets
std = {"arvind", "arvind", "Jyothi","Raj","Sridhar"}
print(type(std))
print(std)
print("----------------------------------------------")
std.add("Pooja")
print(std)
print("----------------------------------------------")
std.pop()
print(std)
print("----------------------------------------------")
std.remove("arvind")
print(std)
std.clear()
print(std)